baseURL = 'https://confluentinc.github.io/live-labs/'
languageCode = 'en-us'
title = 'Confluent Live Labs'
canonifyURLs = true
theme = "hugo-theme-learn"

# For search functionality
[outputs]
  home = [ "HTML", "RSS", "JSON"]

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "confluent"
  DisableShortcutsTitle = true
  disableMermaid = true

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
identifier = "gh"
url = "https://github.com/confluentinc/live-labs"
weight = 10